### ISSUE TITLE
RegressionTables v0.0.2 is incompatible with DataFrames v0.11.1

### ISSUE THREAD

**Issue by ltf-canada** [jmboehm/RegressionTables.jl#4] opened 2017-12-05 16:19 UTC
Installing RegressionTables on Julia v0.6.1 forces a DataFrames downgrade to v0.10.1.

**Comment by floswald** [comment] 2017-12-05 16:28
from the REQUIRE it seems that this is caused by another dependency (distributions?). there are many packages out there not yet on DataFrames v0.11.1. it's going to be some work to figure out which ones. That said, @jmboehm why do you require `Distributions 0.4.6`? i see that's from march 2014?

**Comment by floswald** [comment] 2017-12-05 16:40
oh i just learned that `Distributions 0.4.6` means that you have to have *at least* that version. still, i can only get the new dataframes working in a completely separate `JULIA_PKGDIR`. there's just too many old dependencies around still.

**Comment by floswald** [comment] 2018-01-26 08:19
i think this is because of the dependency on https://github.com/matthieugomez/FixedEffectModels.jl/issues/21

**Comment by floswald** [comment] 2018-02-02 08:32
the latest release doesn't work for me yet:

```
└─version range [0.9.0,0.11.0) required by package FixedEffectModels, whose allowed version range is [0.4.0,∞):
  └─version range [0.4.0,∞) required by package RegressionTables, whose allowed version range is [0.0.0-,∞):
    └─[see above for RegressionTables backtrace]
```

maybe you have to explicitly require FixedEffectModels 0.5.0 in your REQUIRE?

**Comment by floswald** [comment] 2018-02-02 08:56
hmm, it's odd because I can see that travis installs FixedEffectModels 0.5.0 for you and all is fine.

**Comment by jmboehm** [comment] 2018-02-02 15:22
Yeah, I also sometimes run into these issues... try removing & freeing both and then adding them, for some reason this sometimes works for me.

**Comment by jmboehm** [comment] 2018-02-02 15:24
I'm now requiring FixedEffectModels 0.5.0, let me know whether this helps.

**Comment by jmboehm** [comment] 2018-02-12 05:34
Fixed in commit c0de1336ee90899152f1a65beee449611a0495ab

**Closed by jmboehm** 2018-02-12 05:34 UTC
