### ISSUE TITLE
Error: p value = NaN, but it needs to be non-negative

### ISSUE THREAD

**Issue by PharmCat** [jmboehm/RegressionTables.jl#117] opened 2022-07-23 12:00 UTC
Yes it's really NaN when using `dropcollinear = true` is it possible to work with this types of models?

```
julia> olscmax
StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

:(log(Cmax)) ~ 1 + Sequence + Period + Formulation + Subject

Coefficients:
────────────────────────────────────────────────────────────────────────────────────
                     Coef.   Std. Error       t  Pr(>|t|)     Lower 95%    Upper 95%
────────────────────────────────────────────────────────────────────────────────────
(Intercept)      6.46193      0.077827    83.03    <1e-28    6.30052       6.62333
Sequence: tr    -0.0143149    0.105746    -0.14    0.8935   -0.233619      0.204989
Period: 2        0.039951     0.0305263    1.31    0.2041   -0.0233566     0.103259
Formulation: t   0.0358771    0.0305263    1.18    0.2524   -0.0274304     0.0991847
Subject: 2       0.518319     0.105746     4.90    <1e-04    0.299015      0.737623
Subject: 3       0.301846     0.105746     2.85    0.0092    0.082542      0.52115
Subject: 4       0.0409981    0.105746     0.39    0.7020   -0.178306      0.260302
Subject: 5      -0.596241     0.105746    -5.64    <1e-04   -0.815545     -0.376937
Subject: 6      -0.950327     0.105746    -8.99    <1e-08   -1.16963      -0.731023
Subject: 7       0.115056     0.105746     1.09    0.2884   -0.104247      0.33436
Subject: 8       0.61519      0.105746     5.82    <1e-05    0.395887      0.834494
Subject: 9       0.674252     0.105746     6.38    <1e-05    0.454948      0.893555
Subject: 10      0.843855     0.105746     7.98    <1e-07    0.624551      1.06316
Subject: 11      0.32713      0.105746     3.09    0.0053    0.107826      0.546434
Subject: 12      0.556382     0.105746     5.26    <1e-04    0.337078      0.775686
Subject: 13     -0.277867     0.105746    -2.63    0.0154   -0.49717      -0.0585627
Subject: 14     -0.690512     0.105746    -6.53    <1e-05   -0.909816     -0.471208
Subject: 15      0.0        NaN          NaN       NaN     NaN           NaN
Subject: 16     -0.0551107    0.105746    -0.52    0.6075   -0.274415      0.164193
Subject: 17     -0.324189     0.105746    -3.07    0.0057   -0.543493     -0.104885
Subject: 18     -0.237008     0.105746    -2.24    0.0354   -0.456312     -0.017704
Subject: 19     -0.461697     0.105746    -4.37    0.0002   -0.681001     -0.242393
Subject: 20     -0.234932     0.105746    -2.22    0.0369   -0.454236     -0.0156284
Subject: 21     -0.859009     0.105746    -8.12    <1e-07   -1.07831      -0.639705
Subject: 22      0.7923       0.105746     7.49    <1e-06    0.572996      1.0116
Subject: 23     -0.256151     0.105746    -2.42    0.0241   -0.475455     -0.0368475
Subject: 24      0.21707      0.105746     2.05    0.0522   -0.00223418    0.436374
────────────────────────────────────────────────────────────────────────────────────

julia> regtable(olscmax; renderSettings = latexOutput())
┌ Error: p value = NaN, but it needs to be non-negative
```

**Comment by jmboehm** [comment] 2022-07-24 10:55
I think I know what the issue is, but could you post a replicable example so that I can test the solution?

**Comment by PharmCat** [comment] 2022-07-24 12:46
> I think I know what the issue is, but could you post a replicable example so that I can test the solution?

Yep!

Data:

```
Subject	Sequence	Period	Formulation	Var
3	TR	1	T	225.95
1	RT	1	R	181.09
2	RT	1	R	114.48
4	RT	1	R	176.91
5	TR	1	T	147.01
6	TR	1	T	97.53
7	RT	1	R	146.60
8	TR	1	T	45.58
9	RT	1	R	109.20
10	RT	1	R	125.61
11	TR	1	T	92.26
12	RT	1	R	237.95
13	TR	1	T	145.46
14	TR	1	T	179.96
15	TR	1	T	173.86
16	RT	1	R	144.00
17	RT	1	R	185.10
18	TR	1	T	117.99
1	RT	2	T	210.14
2	RT	2	T	98.72
3	TR	2	R	241.09
4	RT	2	T	186.65
5	TR	2	R	139.56
6	TR	2	R	124.77
7	RT	2	T	137.62
8	TR	2	R	57.71
9	RT	2	T	139.36
10	RT	2	T	120.43
11	TR	2	R	116.10
12	RT	2	T	228.63
13	TR	2	R	165.09
14	TR	2	R	181.09
15	TR	2	R	206.66
16	RT	2	T	143.25
17	RT	2	T	192.22
18	TR	2	R	125.50
```

Code:

```
Using DataFrames, CSV, GLM, RegressionTables
dfrds        = CSV.File("rds1.csv", types = Dict(:Var => Float64, :Subject => String, :Period => String, :Sequence => String, :Formulation => String )) |> DataFrame
olscmax  = lm(@formula(log(Var) ~ Sequence+Period+Formulation+Subject), dfrds; dropcollinear = true,)
regtable(olscmax)
```

**Comment by jmboehm** [comment] 2022-07-25 06:59
Great, thank you, I can replicate this.

**Comment by jmboehm** [comment] 2022-07-25 07:25
Fixed by #118

**Closed by jmboehm** 2022-07-25 07:25 UTC
